name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.2'

      - name: Build Windows Binary
        run: go build -o share.exe main.go

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: share.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
